#!/usr/bin/bash

build() {
    add_binary "lvm"
    add_binary "lvmetad"
    add_binary "cryptsetup"
    add_binary "shred"
    add_binary "dmsetup"
    add_binary "mkfs"
    add_binary "mkfs.ext4"
    add_binary "mkswap"
    add_binary "swapon"

    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/udev/rules.d/11-dm-lvm.rules"
    add_file "/usr/lib/udev/rules.d/69-dm-lvm-metad.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
    add_file "/etc/lvm/lvm.conf"

    add_runscript
}

